'use strict';
const KEY='money-core-v1', defaults=()=>({version:1,starting:0,configured:false,categories:['Tuition','Car','Miscellaneous','Food','Shopping','Bills','Entertainment','Income','Other'],transactions:[],budgets:{}});
let state=defaults(),view='dashboard',filters={search:'',category:'',type:'',from:'',to:''};
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},month=today().slice(0,7),colors=['#a0f4c4','#75d8e6','#e7bc73','#b3a1de','#ee9994','#93acde','#c5cc83','#d8a778','#829da5'];
function notify(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').style.display='none',3200)}
function valid(x){return x&&x.version===1&&Number.isSafeInteger(x.starting)&&x.starting>=0&&Array.isArray(x.categories)&&x.categories.length<=100&&x.categories.every(c=>typeof c==='string'&&c.length>0&&c.length<=60)&&new Set(x.categories).size===x.categories.length&&x.budgets&&typeof x.budgets==='object'&&Object.values(x.budgets).every(v=>Number.isSafeInteger(v)&&v>=0)&&Array.isArray(x.transactions)&&x.transactions.length<=50000&&new Set(x.transactions.map(t=>t.id)).size===x.transactions.length&&x.transactions.every(t=>typeof t.id==='string'&&typeof t.name==='string'&&t.name.length<=100&&Number.isSafeInteger(t.amount)&&t.amount>0&&['income','expense'].includes(t.type)&&x.categories.includes(t.category)&&/^\d{4}-\d{2}-\d{2}$/.test(t.date)&&!Number.isNaN(new Date(t.date).getTime())&&(!t.note||typeof t.note==='string')&&(!t.detail||typeof t.detail==='string'))}
try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);if(!valid(x))throw Error();state=x}}catch(e){notify('Saved data could not load. Import a backup in Settings.');}
function commit(next){try{localStorage.setItem(KEY,JSON.stringify(next));state=next;render();return true}catch(e){notify('Could not save. Export a backup or free browser storage.');return false}}
const totals=ts=>ts.reduce((a,t)=>(a[t.type]+=t.amount,a),{income:0,expense:0});
const all=()=>totals(state.transactions), balance=()=>state.starting+all().income-all().expense;
const sumCat=(c,monthly=false)=>state.transactions.filter(t=>t.type==='expense'&&t.category===c&&(!monthly||t.date.startsWith(month))).reduce((a,t)=>a+t.amount,0);
const panel=(title,body,extra='')=>`<section class="panel"><div class="panel-head"><h2>${title}</h2>${extra}</div>${body}</section>`;
const empty=(title,desc)=>`<div class="empty"><strong>${title}</strong>${desc}</div>`;
const navs=[['dashboard','◈','Overview'],['transactions','≡','Transactions'],['analytics','▥','Analytics'],['tuition','▣','Tuition'],['car','◇','Car'],['categories','⊞','Categories'],['settings','⚙','Settings']];
$('#today').textContent=new Date().toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
function navigate(v){view=v;filters={search:'',category:'',type:'',from:'',to:''};render()}
function render(){ $('#nav').innerHTML=navs.map(([id,icon,n])=>`<button data-nav="${id}" class="${view===id?'active':''}"><b>${icon}</b>${n}</button>`).join('');$('#title').textContent=navs.find(n=>n[0]===view)[2];$('#content').innerHTML=({dashboard:dashboard,transactions:transactions,analytics:analytics,tuition:()=>dedicated('Tuition'),car:()=>dedicated('Car'),categories:categories,settings:settings})[view](); }
function metric(label,value,caption,cls=''){return `<div class="panel metric"><div class="small-label">${label}</div><strong class="${cls}">${money(value)}</strong><small>${caption}</small></div>`}
function core(){const a=all(),base=state.starting+a.income,p=base?Math.max(0,Math.min(100,Math.round(balance()/base*100))):0;return `<section class="panel balance-panel"><div><div class="small-label">AVAILABLE BALANCE</div><div class="balance">${money(balance())}</div><div class="hint"><span class="led"></span> ${balance()<0?'Balance below zero':state.configured?'Balance monitor active':'Ready for your starting balance'}</div><button data-action="balance" style="margin-top:15px">Set starting balance</button></div><div class="gauge" style="--p:${p}"><div class="gauge-inner"><strong>${p}%</strong><small>MONEY REMAINING</small></div></div></section>`}
function dashboard(){const a=all();return `${!state.configured?`<div class="setup"><div><strong>Initialize your Money Core</strong><p>Enter the money you have today, then track new income and expenses.</p></div><button class="primary" data-action="balance">Set starting balance</button></div>`:''}<div class="hero-grid">${core()}${panel('Spending breakdown',donut(),'<span class="tag">ALL TIME</span>')}</div><div class="metrics">${metric('TOTAL INCOME',a.income,'Since you started tracking','green')}${metric('TOTAL SPENT',a.expense,'Across all categories','red')}${metric('THIS MONTH',totals(state.transactions.filter(t=>t.date.startsWith(month))).expense,new Date().toLocaleDateString('en-US',{month:'long',year:'numeric'}))}</div><div class="columns">${panel('Balance timeline',lineChart())}${panel('Monthly budgets',budgetList(),'<button data-nav="categories">Manage</button>')}</div>${panel('Recent transactions',table([...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5)),'<button data-nav="transactions">View all</button>')}`}
function donut(ts=state.transactions){const groups=state.categories.map((c,i)=>({c,i,n:ts.filter(t=>t.category===c&&t.type==='expense').reduce((s,t)=>s+t.amount,0)})).filter(x=>x.n);const total=groups.reduce((s,x)=>s+x.n,0);if(!total)return empty('No spending yet','Add an expense to see where your money goes.');let p=0;const stops=groups.map(x=>{const start=p;p+=x.n/total*100;return `${colors[x.i%colors.length]} ${start}% ${p}%`}).join(',');return `<div class="spend-layout"><div class="donut" style="background:conic-gradient(${stops})"><span>${money(total)}<small>TOTAL SPENT</small></span></div><div class="category-list">${groups.sort((a,b)=>b.n-a.n).map(x=>`<div class="category-row"><span><i class="swatch" style="background:${colors[x.i%colors.length]}"></i>${esc(x.c)}</span><span>${money(x.n)} <small>${Math.round(x.n/total*100)}%</small></span></div>`).join('')}</div></div>`}
function lineChart(ts=state.transactions){if(!ts.length)return empty('Your balance story starts here','Each transaction adds a point to this chart.');const dates=[...new Set(ts.map(t=>t.date))].sort();let b=state.starting,points=[b];dates.forEach(d=>{ts.filter(t=>t.date===d).forEach(t=>b+=t.type==='income'?t.amount:-t.amount);points.push(b)});const min=Math.min(0,...points),max=Math.max(100,...points),range=max-min;const coords=points.map((v,i)=>`${50+i/(points.length-1)*520},${145-(v-min)/range*120}`);return `<svg class="chart" viewBox="0 0 610 185" role="img" aria-label="Balance over time"><defs><linearGradient id="fade" x2="0" y2="1"><stop stop-color="#a0f4c4" stop-opacity=".22"/><stop offset="1" stop-color="#a0f4c4" stop-opacity="0"/></linearGradient></defs>${[25,65,105,145].map(y=>`<line x1="50" x2="580" y1="${y}" y2="${y}" stroke="#ffffff0d"/>`).join('')}<path d="M${coords.join(' L')} L570,145 L50,145 Z" fill="url(#fade)"/><polyline points="${coords.join(' ')}" fill="none" stroke="#a0f4c4" stroke-width="3" stroke-linejoin="round"/>${coords.map((c,i)=>`<circle cx="${c.split(',')[0]}" cy="${c.split(',')[1]}" r="4" fill="#a0f4c4"><title>${i?dates[i-1]:'Starting balance'}: ${money(points[i])}</title></circle>`).join('')}<text x="50" y="174">START</text><text x="570" y="174" text-anchor="end">${dates.at(-1)}</text><text x="50" y="16">${money(max)}</text></svg>`}
function budgetList(){const entries=Object.entries(state.budgets).filter(([,v])=>v>0);if(!entries.length)return empty('Give your spending a limit','Set monthly budgets in Categories.');return entries.map(([c,v])=>{const spent=sumCat(c,true),pct=Math.round(spent/v*100),color=pct>=100?'var(--red)':pct>=70?'var(--amber)':'var(--green)';return `<div class="budget"><div class="budget-top"><span>${esc(c)}</span><span>${money(spent)} <span style="color:var(--muted)">/ ${money(v)}</span></span></div><div class="track"><span style="width:${Math.min(100,pct)}%;background:${color}"></span></div><div class="budget-meta" style="color:${color}">${pct}% used${pct>=100?' · Budget exceeded':pct>=90?' · Near your limit':pct>=70?' · Watch your spending':''}</div></div>`}).join('')}
function table(ts){if(!ts.length)return empty('No transactions here','Add a transaction or adjust your filters.');return `<div class="table-wrap"><table><thead><tr><th>TRANSACTION</th><th>DATE</th><th>CATEGORY</th><th>AMOUNT</th><th>ACTIONS</th></tr></thead><tbody>${ts.map(t=>`<tr><td><strong>${esc(t.name)}</strong>${t.detail||t.note?`<small>${esc(t.detail)}${t.detail&&t.note?' · ':''}${esc(t.note)}</small>`:''}</td><td>${esc(t.date)}</td><td><span class="pill">${esc(t.category)}</span></td><td class="${t.type==='income'?'green':'red'}" style="white-space:nowrap">${t.type==='income'?'+':'−'}${money(t.amount)}</td><td class="actions"><button data-edit="${esc(t.id)}">Edit</button><button data-delete="${esc(t.id)}" aria-label="Delete ${esc(t.name)}">✕</button></td></tr>`).join('')}</tbody></table></div>`}
function filtered(){return state.transactions.filter(t=>(!filters.category||t.category===filters.category)&&(!filters.type||t.type===filters.type)&&(!filters.from||t.date>=filters.from)&&(!filters.to||t.date<=filters.to)&&`${t.name} ${t.detail||''} ${t.note||''}`.toLowerCase().includes(filters.search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date))}
function transactions(){return panel('Transaction log',`<div class="filters"><input aria-label="Search transactions" placeholder="Search transactions…" data-filter="search" value="${esc(filters.search)}"><select aria-label="Filter category" data-filter="category"><option value="">All categories</option>${state.categories.map(c=>`<option ${filters.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select aria-label="Filter type" data-filter="type"><option value="">All types</option><option value="income" ${filters.type==='income'?'selected':''}>Income</option><option value="expense" ${filters.type==='expense'?'selected':''}>Expense</option></select><input aria-label="From date" type="date" data-filter="from" value="${filters.from}"><input aria-label="To date" type="date" data-filter="to" value="${filters.to}"></div><div id="table-result">${table(filtered())}</div>`)}
function monthlyBars(){const months=[...new Set(state.transactions.map(t=>t.date.slice(0,7)))].sort().slice(-12);if(!months.length)return empty('No monthly data yet','Monthly totals appear as you track transactions.');const vals=months.map(m=>totals(state.transactions.filter(t=>t.date.startsWith(m))));const max=Math.max(1,...vals.flatMap(t=>[t.income,t.expense]));return `<div class="legend"><span><i class="swatch" style="background:var(--green)"></i>Income</span><span><i class="swatch" style="background:var(--red)"></i>Expenses</span></div>${months.map((m,i)=>`<div class="bar-row"><span>${m}</span><div><div class="bar" style="width:${vals[i].income/max*100}%;background:var(--green);margin-bottom:5px" title="Income ${money(vals[i].income)}"></div><div class="bar" style="width:${vals[i].expense/max*100}%;background:var(--red)" title="Expenses ${money(vals[i].expense)}"></div></div><small>${money(vals[i].expense)}</small></div>`).join('')}`}
function analytics(){const a=all(),max=Math.max(1,a.income,a.expense);return `<div class="columns">${panel('Spending by category',donut())}${panel('Income vs. expenses',`<div class="bar-row"><span>Income</span><div class="bar" style="width:${a.income/max*100}%;background:var(--green)"></div><span>${money(a.income)}</span></div><div class="bar-row"><span>Expenses</span><div class="bar" style="width:${a.expense/max*100}%;background:var(--red)"></div><span>${money(a.expense)}</span></div>`)}</div>${panel('Balance over time',lineChart())}<div class="columns">${panel('Monthly cash flow',monthlyBars())}${panel('Budget distribution',budgetList())}</div>`}
function dedicated(c){const ts=state.transactions.filter(t=>t.category===c),groups={};ts.filter(t=>t.type==='expense').forEach(t=>{const key=t.detail||'General';groups[key]=(groups[key]||0)+t.amount});const max=Math.max(1,...Object.values(groups));return `<div class="metrics">${metric(`TOTAL ${c==='Tuition'?'EDUCATION':'CAR'} SPENDING`,sumCat(c),'All time','red')}${metric('THIS MONTH',sumCat(c,true),'Current calendar month')}${metric('MONTHLY BUDGET',state.budgets[c]||0,'Set in Categories')}</div><div class="columns">${panel('Cost breakdown',Object.keys(groups).length?Object.entries(groups).map(([n,v])=>`<div class="bar-row"><span>${esc(n)}</span><div class="bar" style="width:${v/max*100}%"></div><span>${money(v)}</span></div>`).join(''):empty(`Track your ${c.toLowerCase()} costs`,'Use the detail field to track books, fees, insurance, gas and more.'))}${panel(`${c} spending`,donut(ts))}</div>${panel(`${c} transactions`,table(ts.sort((a,b)=>b.date.localeCompare(a.date))),`<button class="primary" data-add-category="${c}">＋ Add ${c.toLowerCase()} expense</button>`)}`}
function categories(){return `<div class="columns">${panel('Categories & monthly budgets',`<p class="hint">Set a monthly spending limit. Leave zero for no budget.</p><form id="budgets">${state.categories.filter(c=>c!=='Income').map(c=>`<label>${esc(c)}<input aria-label="${esc(c)} monthly budget" type="number" min="0" max="999999999" step="0.01" data-budget="${esc(c)}" value="${(state.budgets[c]||0)/100}"></label>`).join('')}<button class="primary">Save budgets</button></form>`)}${panel('Create a category',`<form id="category-form"><label>Category name<input name="category" maxlength="60" required placeholder="e.g. Travel"></label><button class="primary">Add category</button></form><p class="hint">Categories can be used in transactions and monthly budgets.</p>`)}</div>`}
function settings(){return `<div class="settings-grid">${panel('Balance settings',`<form id="starting-form"><label>Starting balance ($)<input name="starting" type="number" min="0" max="999999999" step="0.01" value="${state.starting/100}" required></label><p class="hint">Enter what you had before your first recorded transaction. Your current balance includes all income and expenses.</p><button class="primary">Save starting balance</button></form>`)}${panel('Data & backups',`<div class="setting-row"><div><h3>Full backup</h3><p>Balance, transactions, categories and budgets.</p></div><button data-action="export">Export JSON</button></div><div class="setting-row"><div><h3>Transaction spreadsheet</h3><p>Download a CSV to open in Excel.</p></div><button data-action="csv">Export CSV</button></div><div class="setting-row"><div><h3>Restore a backup</h3><p>Import a Money Core JSON backup.</p></div><button data-action="import">Import</button><input id="import-file" type="file" accept="application/json,.json" hidden></div><div class="setting-row"><div><h3 class="danger">Reset all data</h3><p>Delete all saved financial information.</p></div><button class="danger" data-action="reset">Reset</button></div>`)}${panel('Storage status',`<p class="hint">Your financial data is saved only in this browser on this device. It does not sync between devices. Clearing browser data will remove it. Export a JSON backup regularly.</p><span class="tag">${state.transactions.length} TRANSACTIONS SAVED</span>`)}</div>`}
function openTransaction(id,c){const t=state.transactions.find(t=>t.id===id);$('#form').reset();$('#modal-title').textContent=t?'Edit transaction':'Add transaction';$('#form').elements.category.innerHTML=state.categories.map(c=>`<option>${esc(c)}</option>`).join('');$('#form').elements.date.value=today();if(t)for(const [k,v] of Object.entries(t)){if($('#form').elements[k])$('#form').elements[k].value=k==='amount'?v/100:v}if(c)$('#form').elements.category.value=c;$('#modal').showModal();$('#form').elements.name.focus()}
$('#add').onclick=()=>openTransaction();$('#close').onclick=()=>$('#modal').close();
$('#form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),amount=Math.round(Number(data.amount)*100);if(!Number.isSafeInteger(amount)||amount<=0)return notify('Enter a valid positive amount.');const t={...data,amount,id:data.id||crypto.randomUUID()};const next=structuredClone(state),i=next.transactions.findIndex(x=>x.id===t.id);if(i>=0)next.transactions[i]=t;else next.transactions.push(t);if(commit(next)){$('#modal').close();notify(i>=0?'Transaction updated':'Transaction saved')}};
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function action(a){if(a==='balance'){navigate('settings');$('#starting-form input').focus()}if(a==='export')download(`money-core-${today()}.json`,JSON.stringify(state,null,2),'application/json');if(a==='csv'){const rows=[['Date','Name','Type','Category','Amount','Detail','Note'],...state.transactions.map(t=>[t.date,t.name,t.type,t.category,(t.amount/100).toFixed(2),t.detail,t.note])];const csv=rows.map(r=>r.map(v=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}).join(',')).join('\r\n');download(`transactions-${today()}.csv`,csv,'text/csv;charset=utf-8')}if(a==='import')$('#import-file').click();if(a==='reset'&&confirm('Delete ALL transactions, balances, categories and budgets? Export a backup first.')){if(commit(defaults()))notify('All data reset')}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.nav)navigate(b.dataset.nav);if(b.dataset.action)action(b.dataset.action);if(b.dataset.addCategory)openTransaction(null,b.dataset.addCategory);if(b.dataset.edit)openTransaction(b.dataset.edit);if(b.dataset.delete&&confirm('Delete this transaction?')){const next=structuredClone(state);next.transactions=next.transactions.filter(t=>t.id!==b.dataset.delete);if(commit(next))notify('Transaction deleted')}});
document.addEventListener('input',e=>{if(e.target.dataset.filter){filters[e.target.dataset.filter]=e.target.value;$('#table-result').innerHTML=table(filtered())}});
document.addEventListener('submit',e=>{if(e.target.id==='starting-form'){e.preventDefault();const next=structuredClone(state);next.starting=Math.round(Number(e.target.elements.starting.value)*100);next.configured=true;if(commit(next))notify('Starting balance saved')}if(e.target.id==='budgets'){e.preventDefault();const next=structuredClone(state);e.target.querySelectorAll('[data-budget]').forEach(x=>next.budgets[x.dataset.budget]=Math.round(Number(x.value)*100));if(commit(next))notify('Budgets saved')}if(e.target.id==='category-form'){e.preventDefault();const c=e.target.elements.category.value.trim();if(!c)return;if(state.categories.some(x=>x.toLowerCase()===c.toLowerCase()))return notify('That category already exists.');const next=structuredClone(state);next.categories.push(c);if(commit(next))notify('Category added')}});
document.addEventListener('change',async e=>{if(e.target.id!=='import-file'||!e.target.files[0])return;try{const f=e.target.files[0];if(f.size>10000000)throw Error();const x=JSON.parse(await f.text());if(!valid(x))throw Error();if(confirm(`Replace current data with this backup (${x.transactions.length} transactions)?`)){if(commit(x))notify('Backup restored')}}catch(err){notify('Invalid backup. Choose a Money Core JSON export.')}e.target.value=''});
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{const x=JSON.parse(e.newValue);if(valid(x)){state=x;render()}}catch{}}});
render();
